#!/usr/bin/env python

from glob import glob
from cursesapp import CursesApp,BoxWindow
import curses

class FileListWindow(BoxWindow):
    def __init__(self, bottom,right,top,left,stdscr, path="."):
        self.path = path
        self.refresh_filelist()
        super(FileListWindow, self).__init__(bottom,right,top,left,stdscr)

    def refresh_filelist(self):
        self.filelist = glob("{}/*".format(self.path))

    def __str__(self):
        return "\n".join(self.filelist)

class FMC(CursesApp):
    def layout(self):
        y,x = self.stdscr.getmaxyx()
        self.filewin = FileListWindow(y,x,0,0,self.stdscr, ".")
        self.filewin.colors = curses.color_pair(2)
        self.filewin.win.bkgd(' ', self.filewin.colors)
        self.windows = [self.filewin]
        self.render()

    def handle_key(self, key):
        if key == ord('q'):
            self.quit = True
        elif key == ord('r'):
            self.filewin.refresh_filelist()

app = FMC()
app.run()
